OBJECTS = main-linux.o AsteroidsVR.o ogre-linux.o Asteroid.o AsteroidField.o

CXXFLAGS = -g -I/usr/include/OGRE -I/usr/include/OGRE/RenderSystems/GL
LDFLAGS = -L/usr/lib/x86_64-linux-gnu -lOgreMain -lboost_system -lOIS

AsteroidsVR: $(OBJECTS)
	$(CXX) -o $@ $(OBJECTS) $(LDFLAGS)

clean:
	rm -f $(OBJECTS) AsteroidsVR.so
